/* 文字列 */
#define ID_ST_APLNAME	2
#define ID_ST_TRVOBJ	3

#define ID_ST_MEM	20

#define ID_ST_RDONLY	40
#define ID_ST_NOPNBUSY	42
#define ID_ST_OPNBUSY	44
#define ID_ST_NACSES	46
#define ID_ST_NOPENFILE	47

#define ID_ST_NFNDLINK	60
#define ID_ST_NREADLINK	61
#define ID_ST_NREGVOBJ	62
#define ID_ST_ILLTAD	63
#define ID_ST_NWRONL	65

#define ID_ST_NDELLINK	80
#define ID_ST_NWLINK	81
#define ID_ST_NWFILE	82
#define ID_ST_NMKNEWFILE	83
#define ID_ST_NWDATA	84

#define ID_ST_NPASTE	100


/* パネル */
#define ID_PN_ERR1	10000
#define ID_PN_SAVE	10001

#define ID_PN_SAVE_OK	0
#define ID_PN_SAVE_NO	1
#define ID_PN_SAVE_CANCEL	2


/* メニュー */
#define ID_MN	1

#define ID_MN_END		0
#define ID_MN_SAVE		1
#define ID_MN_VIEW		2
#define ID_MN_EDIT		3
#define ID_MN_PROTECT	4
#define ID_MN_VOBJ		5
#define ID_MN_OBJ		6
#define ID_MN_FUSEN		7
#define ID_MN_DISK		8
#define ID_MN_WND		9
#define ID_MN_APPLET	10
#define ID_MN_EXEC		11

#define ID_MN_VIEW_FULLWND	1
#define ID_MN_VIEW_REPAINT	2

#define ID_MN_SAVE_NEWFILE	1
#define ID_MN_SAVE_OLDFILE	2

#define ID_MN_EDIT_COPY	1
#define ID_MN_EDIT_CPPASTE	2
#define ID_MN_EDIT_MOVE	3
#define ID_MN_EDIT_MVPASTE	4
#define ID_MN_EDIT_DELETE	5
#define ID_MN_EDIT_ALL	7
#define ID_MN_EDIT_FRONT	9
#define ID_MN_EDIT_BACK	10

#define ID_MN_PROTECT_FIX	1
#define ID_MN_PROTECT_UNFIX	2
#define ID_MN_PROTECT_BACK	4
#define ID_MN_PROTECT_UNBACK	5
